# Generated by Django 4.2.29 on 2026-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('OTP', 'OTP'), ('LOAN_APPROVED', 'LOAN_APPROVED'), ('DISBURSEMENT_SUCCESS', 'DISBURSEMENT_SUCCESS'), ('PAYMENT_RECEIVED', 'PAYMENT_RECEIVED')], default='OTP', max_length=30),
        ),
    ]
