# Generated by Django 4.2.29 on 2026-04-29 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenor', models.IntegerField(help_text='Loan tenor in days')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('REVIEW', 'REVIEW')], default='PENDING', max_length=20)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
