# Generated by Django 4.2.29 on 2026-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
