# Generated by Django 4.2.29 on 2026-04-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DISBURSED', 'DISBURSED'), ('DECLINED', 'DECLINED'), ('REVIEW', 'REVIEW'), ('REPAID', 'REPAID')], default='PENDING', max_length=20),
        ),
    ]
