# Generated by Django 4.2.29 on 2026-04-30 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCVerification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("verification_type", models.CharField(choices=[("BVN", "BVN"), ("NIN", "NIN")], max_length=10)),
                ("identifier", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("SUCCESS", "SUCCESS"), ("FAILED", "FAILED")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="kycverification",
            index=models.Index(fields=["user", "verification_type", "identifier"], name="kyc_kycver_user_id_0fb2cd_idx"),
        ),
    ]
