# Generated by Django 4.2.29 on 2026-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymentschedule',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
